### ISSUE TITLE
How to generate nforA.exr and nforB.exr？

### ISSUE THREAD

**Issue by LZleejean** [Mike-Leo-Smith/Ensemble-Denoising#1]
In my view, the nfor.exr can be generated from color, colorA, colorB and many other features.

But hot to generate nforA.exr or nforB.exr？

Is nforA.exr generated from colorA, colorAA, colorAB and other features？

**Comment by Mike-Leo-Smith** [comment]
Generating `colorA.exr` and `colorB.exr` from `colorAA.exr`, `colorAB.exr`, `colorBA.exr`, etc. is one solution.

Another approach without the need for extra storage and computation (as we adopted in the paper), is simply using the intermediate filtering results of `colorA.exr` and `colorB.exr`in the NFOR algorithm (see [these lines](https://github.com/tunabrain/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/denoiser/denoiser.cpp#L96), just dump `resultA` and `resultB` in the code). They are slightly noisier and correlated, but OK for use in our method since we perform further filtering on the weight maps.

**Comment by LZleejean** [comment]
> Generating `colorA.exr` and `colorB.exr` from `colorAA.exr`, `colorAB.exr`, `colorBA.exr`, etc. is one solution.
> 
> Another approach without the need for extra storage and computation (as we adopted in the paper), is simply using the intermediate filtering results of `colorA.exr` and `colorB.exr`in the NFOR algorithm (see [these lines](https://github.com/tunabrain/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/denoiser/denoiser.cpp#L96), just dump `resultA` and `resultB` in the code). They are slightly noisier and correlated, but OK for use in our method since we perform further filtering on the weight maps.

Thank you for your reply. It addressed my concern. By the way, how to generate `kpcnA.exr` and `kpcnB.exr`?

**Comment by Mike-Leo-Smith** [comment]
If I recall it correctly, we generate `kpcnA.exr` and `kpcnB.exr` by re-running the network, with the same auxiliary feature maps as `kpcn.exr`.

**Comment by LZleejean** [comment]
Specifically, just change the color into the colorA and others auxiliary features are fixed. Is it correct?

**Comment by Mike-Leo-Smith** [comment]
Yes

**Comment by LZleejean** [comment]
Thank you for your efficient response and help.

**Comment by Mike-Leo-Smith** [comment]
Oh, one more thing: KPCN splits color buffers into diffuse and specular illumination and denoise them separatedly, so actually you also need to replace `diffuse.exr` with `diffuseA/B.exr` and `specular.exr` with `specularA/B.exr`.

**Comment by LZleejean** [comment]
> Oh, one more thing: KPCN splits color buffers into diffuse and specular illumination and denoise them separatedly, so actually you also need to replace `diffuse.exr` with `diffuseA/B.exr` and `specular.exr` with `specularA/B.exr`.

Yes, I will just fix the auxiliary features, such as albedo, normal, depth, respective half buffer and variance.
